a.out: main.cpp  ./src/weatherdata.cpp ./src/forecastcondition.cpp ./src/currentcondition.cpp
	g++ main.cpp ./src/currentcondition.cpp ./src/weatherdata.cpp ./src/forecastcondition.cpp 


clear:
	rm -f a.out ./myinclude/*.gch